title: Rust-blog
description: Blog about Rust programming language
url: "https://rust-develop.github.io"
baseurl: ""

author:
  name: rust-develop

theme: minima

minima:
  skin: dark

header_pages:
  - about.md

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

permalink: /:year/:month/:day/:title/
